import { LanguageData, AppLanguage, VisitDetail } from "../../types/types";

export const languageData: LanguageData[] = [
  {
    locale: "en",
    translation: {
      welcome: "Welcome!",
      trackVisits:
        "Keep track of all your visits and export data whenever you need it.",
      loginEmailPrompt: "Enter your email to login",
      registerEmailPrompt: "Enter your email to get started",
      pleaseLoginHere: "Please Login Here!",
      emailAddress: "Email Address",
      agencyName: "Agency Name",
      ownerName: "Owner’s Name",
      email: "E-mail",
      password: "Password",
      forgotPassword: "Forget Password?",
      rememberme: "Remember me",
      donthaveaccount: "Don’t have account?",
      recoverAccount: "Recover Your Account",
      signup: "Sign up",
      or: "OR",
      signIn: "Login",
      pleaseRegisterHere: "Please Register Here!",
      fullname: "Full Name",
      confirmpassword: "Confirm password",
      role: "Role",
      alreadyhaveanaccount: "Already have an account?",
      TermsConditions: "Terms & Conditions",
      registerissucessfullyhaveenjoy: "Register is sucessfully have enjoy!",
      resetpassword: "Reset password",
      enteryouremail: "Input your Email Address",
      rememberyourpassword: "Remember your password?",
      sendOtp: "SEND OTP",
      changePassword: "Change password",
      enternewpassword: "Create the new password",
      invalidEmail: "Please enter a valid email address",
      emailRequired: "Email is required",
      passwordRequired: "Password is required",
      passwordMin: "Password must be at least 6 characters long",
      fullnameRequired: "Full Name is required",
      roleRequired: "Role is required",
      confirmpasswordRequired: "Confirm Password is required",
      passwordsDoNotMatch: "Passwords do not match",
      agencyNameRequired: "Agency Name is required",
      ownerNameRequired: "Owner Name is required",
      passwordsMustMatch: "Passwords must match",
      resetEmail: "Reset Email",
      sendEmail: "Send Email",
      addProperty: "Add Property",
      PhotoUpload: "PhotoUpload",
      photo: "Photo",
      addTitle: "Add Title",
      addDes: "Add Description",
      detail: "Detail",
      desc: "Description",
      otherDet: "Other details",
      submit: "Submit",
      AdFullView: "Ad Full View",
      Notification: "Notification",
      notiReceived: " Notification received",
      notiNew: "New",
      contact: "Contact",
      Email: "Email",
      name: "Name",
      phoneNum: "Phone Number",
      createContact: "Create Contact",
      create: "Create",
      note: "Note",
      home: "Home",
      scheduled: "Scheduled",
      exportData: "Export Data",
      setting: "Setting",
      location: "Location",
      isRequired: "is required",
      title: "Title",
      schedulePropertyVisit: "Schedule Property Visit",
      days: {
        Mo: "Mo",
        Tu: "Tu",
        We: "We",
        Th: "Th",
        Fr: "Fr",
        Sa: "Sa",
        Su: "Su",
      },
      properties: [
        "Flat 1",
        "Room 1",
        "Bed 1",
        "Countryside house 1",
        "House 1",
        "Terrace 1",
        "Stead 1",
      ],
      createSchedule: "Create Schedule",
      clientName: "Client’s Name",
      visitDates: "Visit Dates",
      propertyToVisitors: "Property to Visitors",
      numberOfVisitors: "Number of Visitors",
      numberOfInfants: "Number of Infants",
      AutomatedEmail: "Automated Email",
      visitConfirmed: "Your visit is confirmed",
      visitData: "Visit Data",
      propertyAddress: "Property Address",
      visitDetail: "Visit Details",
      openInGoogleMaps: "Open in Google Maps",
      Whatsapp: "Whatsapp",
      ShareApp: "Share App",
      Copydata: "Copy data",
      dataExport: "Data Export",
      export: "Export",
      clientVisitAppointmentTitle: "Client Visit Appointment Details",
      phone: "Phone",
      Infant: "Infant",
      googleMapsLocation: "Google Maps location",
      viewOnMap: "View on Map",
      calendarData: {
        monthNames: [
          "January",
          "February",
          "March",
          "April",
          "May",
          "June",
          "July",
          "August",
          "September",
          "October",
          "November",
          "December",
        ],
        monthNamesShort: [
          "Jan",
          "Feb",
          "Mar",
          "Apr",
          "May",
          "Jun",
          "Jul",
          "Aug",
          "Sep",
          "Oct",
          "Nov",
          "Dec",
        ],
        dayNames: [
          "Sunday",
          "Monday",
          "Tuesday",
          "Wednesday",
          "Thursday",
          "Friday",
          "Saturday",
        ],
        dayNamesShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        today: "Today",
      },
      selectDateRange: "Select Date Range",
      editProfile: "Edit Profile",
      notification: "Notification",
      language: "Language",
      termsConditions: "Terms & Conditions",
      privacyPolicy: "Privacy Policy",
      signOut: "Sign Out",
      save: "Save",
      effectiveDate: "Effective Date: 6/4/2025",
      accountUse: "1. Account Use",
      accountUseDetails: "Only real estate agencies can register.",
      accountUseDetails1: `Keep your login info secure. You're responsible for your account activity.`,
      appPurpose: "2. App Purpose",
      appPurposeDetails:
        "The app helps agencies manage property listings and client visit schedules.",
      appPurposeDetails1:
        "Clients do not use the app — their data is added manually by agencies.",
      dataPrivacy: "3. Data Privacy",
      dataPrivacyDetails:
        "Each agency's data is private and not shared with others.",
      dataPrivacyDetails1:
        "You own your data and are responsible for its accuracy.",
      communication: "4. Communication",
      communicationDetails:
        "No communication or data sharing is allowed between different agencies.",
      emailsAndSharing: "5. Emails & Sharing",
      emailsAndSharingDetails:
        "The app sends automated emails for visit confirmations.",
      emailsAndSharingDetails1:
        "Sharing options (WhatsApp, copy, etc.) are provided for convenience.",
      DataExport: "6. Data Export",
      dataExportDetails:
        "Agencies can export visit records in Excel for their own use.",
      security: "7. Security",
      securityDetails:
        "We take standard steps to protect data but are not liable for misuse or technical issues.",
      termination: "8. Termination",
      terminationDetails: "Accounts may be suspended if terms are violated.",
      terminationDetails1: "You can request account deletion anytime.",
      Contact: "Contact",
      Eemail: "Email: [Insert Email]",
      Address: "Address: [Insert Address]",
      termsAndConditionsTitle:
        "By using this app, you agree to the following terms:",
      dataWeCollect: "Data We Collect",
      agencyUserDetails: "Agency user details (name, email, password)",
      propertyInfo: "Property info (images, address, description)",
      clientVisitDetails:
        "Client visit details (name, email, phone, visitors count, visit time, property, location)",
      howWeUseIt: "How We Use It",
      secureLogin: "Secure login and account access",
      scheduleManage: "Schedule and manage property visits",
      sendConfirmation: "Send confirmation emails to clients and agency",
      exportVisitData: "Export visit data to Excel for records",
      shareVisitInfo: "Share visit info via WhatsApp or other apps",
      privacySecurity: "Privacy & Security",
      dataIsolation: "Each agency's data is isolated — no inter-agency sharing",
      passwordEncryption: "Passwords are encrypted",
      secureDataStorage:
        "Data stored securely and accessed only by authorized users",
      yourControl: "Your Control",
      accountControl:
        "Agency users can update or delete their data anytime. For account deletion, contact us at [Insert Email].",
      search: "Search",
      noLocation: "Location not available",
      noApartmentsFound: "No Apartments found",
      noContactsFound: "No Contacts found",
      confirmLogout: "Are you sure you want to log out?",
      ok: "OK",
      cancel: "Cancel",
      selectProperty: "Select Property",
      property: "Property",
      visitTime: "Visit Time",
    },
  },
  {
    locale: "sp",
    translation: {
      welcome: "¡Bienvenido!",
      trackVisits:
        "Lleva un registro de todas tus visitas y exporta los datos cuando los necesites.",
      loginEmailPrompt: "Ingresa tu correo electrónico para iniciar sesión.",
      registerEmailPrompt: "Ingresa tu correo electrónico para comenzar.",
      pleaseLoginHere: "¡Por favor, inicia sesión aquí!",
      emailAddress: "Dirección de correo electrónico",
      agencyName: "Nombre de la agencia",
      ownerName: "Nombre del propietario",
      email: "Correo electrónico",
      password: "Contraseña",
      forgotPassword: "¿Olvidaste tu contraseña?",
      rememberme: "Recuérdame",
      donthaveaccount: "¿No tienes cuenta?",
      recoverAccount: "Recupera tu cuenta",
      signup: "Regístrate",
      or: "O",
      signIn: "Iniciar sesión",
      pleaseRegisterHere: "¡Por favor, regístrate aquí!",
      fullname: "Nombre completo",
      confirmpassword: "Confirmar contraseña",
      role: "Rol",
      alreadyhaveanaccount: "¿Ya tienes una cuenta?",
      TermsConditions: "Términos y condiciones",
      registerissucessfullyhaveenjoy: "¡Registro exitoso, disfruta!",
      resetpassword: "Restablecer contraseña",
      enteryouremail: "Ingresa tu dirección de correo electrónico",
      rememberyourpassword: "¿Recuerdas tu contraseña?",
      sendOtp: "ENVIAR CÓDIGO",
      changePassword: "Cambiar contraseña",
      enternewpassword: "Crea la nueva contraseña",
      invalidEmail:
        "Por favor, ingresa una dirección de correo electrónico válida",
      emailRequired: "El correo electrónico es obligatorio",
      passwordRequired: "La contraseña es obligatoria",
      passwordMin: "La contraseña debe tener al menos 6 caracteres",
      fullnameRequired: "El nombre completo es obligatorio",
      roleRequired: "El rol es obligatorio",
      confirmpasswordRequired: "Confirmar contraseña es obligatorio",
      passwordsDoNotMatch: "Las contraseñas no coinciden",
      agencyNameRequired: "El nombre de la agencia es obligatorio",
      ownerNameRequired: "El nombre del propietario es obligatorio",
      passwordsMustMatch: "Las contraseñas deben coincidir",
      resetEmail: "Restablecer correo electrónico",
      sendEmail: "Enviar correo electrónico",
      addProperty: "Agregar propiedad",
      PhotoUpload: "Subir foto",
      photo: "Foto",
      addTitle: "Agregar título...",
      title: "Título",
      schedulePropertyVisit: "Programar visita a la propiedad",
      addDes: "Agregar descripción...",
      detail: "Detalle",
      desc: "Descripción",
      otherDet: "Otros detalles",
      submit: "Enviar",
      AdFullView: "Vista completa del anuncio",
      Notification: "Notificación",
      notiReceived: "Notificación recibida",
      notiNew: "Nuevo",
      contact: "Contacto",
      Email: "Correo electrónico",
      name: "Nombre",
      phoneNum: "Número de teléfono",
      createContact: "Crear Contacto",
      create: "Crear",
      note: "Nota",
      home: "Inicio",
      scheduled: "Programado",
      exportData: "Exportar Datos",
      setting: "Configuración",
      location: "ubicación",
      isRequired: "es obligatorio",
      days: {
        Mo: "Lu",
        Tu: "Ma",
        We: "Mi",
        Th: "Ju",
        Fr: "Vi",
        Sa: "Sa",
        Su: "Do",
      },
      properties: [
        "Piso 1",
        "Habitación 1",
        "Cama 1",
        "Casa de campo 1",
        "Casa 1",
        "Terraza 1",
        "Finca 1",
      ],
      createSchedule: "Crear horario",
      clientName: "Nombre del cliente",
      visitDates: "Fechas de visita",
      propertyToVisitors: "Propiedad para los visitantes",
      numberOfVisitors: "Número de visitantes",
      numberOfInfants: "Número de infantes",
      AutomatedEmail: "Correo electrónico automatizado",
      visitConfirmed: "Tu visita está confirmada",
      visitData: "Datos de la visita",
      propertyAddress: "Dirección de la propiedad",
      visitDetail: "Detalles de la visita",
      openInGoogleMaps: "Abrir en Google Maps",
      Whatsapp: "Whatsapp",
      ShareApp: "Compartir aplicación",
      Copydata: "Copiar datos",
      dataExport: "Exportación de datos",
      export: "Exportar",
      clientVisitAppointmentTitle: "Detalles de la Cita de Visita del Cliente",
      phone: "Teléfono",
      Infant: "Niña",
      googleMapsLocation: "Ubicación en Google Maps",
      viewOnMap: "Ver en el mapa",
      calendarData: {
        monthNames: [
          "Enero",
          "Febrero",
          "Marzo",
          "Abril",
          "Mayo",
          "Junio",
          "Julio",
          "Agosto",
          "Septiembre",
          "Octubre",
          "Noviembre",
          "Diciembre",
        ],
        monthNamesShort: [
          "Ene",
          "Feb",
          "Mar",
          "Abr",
          "May",
          "Jun",
          "Jul",
          "Ago",
          "Sep",
          "Oct",
          "Nov",
          "Dic",
        ],
        dayNames: [
          "Domingo",
          "Lunes",
          "Martes",
          "Miércoles",
          "Jueves",
          "Viernes",
          "Sábado",
        ],
        dayNamesShort: ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa"],
        today: "Hoy",
      },
      selectDateRange: "Seleccionar rango de fechas",
      editProfile: "Editar perfil",
      notification: "Notificación",
      language: "Idioma",
      termsConditions: "Términos y condiciones",
      privacyPolicy: "Política de privacidad",
      signOut: "Cerrar sesión",
      save: "Ahorrar",
      effectiveDate: "Fecha de vigencia: 6/4/2025",
      accountUse: "1. Uso de cuenta",
      accountUseDetails: `Solo las agencias inmobiliarias pueden registrarse.`,
      accountUseDetails1: `Mantén tu información de inicio de sesión segura. Eres responsable de la actividad de tu cuenta.`,
      appPurpose: "2. Propósito de la app",
      appPurposeDetails: `La app ayuda a las agencias a gestionar anuncios de propiedades y horarios de visitas de clientes.`,
      appPurposeDetails1: `Los clientes no usan la app, sus datos son añadidos manualmente por las agencias.`,
      dataPrivacy: "3. Privacidad de los datos",
      dataPrivacyDetails: `Los datos de cada agencia son privados y no se comparten con otras.`,
      dataPrivacyDetails1: `Tú eres dueño de tus datos y eres responsable de su exactitud.`,
      communication: "4. Comunicación",
      communicationDetails: `No se permite la comunicación ni el intercambio de datos entre diferentes agencias.`,
      emailsAndSharing: "5. Correos Electrónicos y Compartir",
      emailsAndSharingDetails: `La app envía correos electrónicos automáticos para confirmar visitas.`,
      emailsAndSharingDetails1: `Se proporcionan opciones para compartir (WhatsApp, copiar, etc.) por conveniencia.`,
      DataExport: "6. Exportación de datos",
      dataExportDetails: `Las agencias pueden exportar los registros de visitas en Excel para su propio uso.`,
      security: "7. Seguridad",
      securityDetails: `Tomamos medidas estándar para proteger los datos, pero no somos responsables de mal uso o problemas técnicos.`,
      termination: "8. Terminación",
      terminationDetails: `Las cuentas pueden ser suspendidas si se violan los términos.`,
      terminationDetails1: `Puedes solicitar la eliminación de la cuenta en cualquier momento.`,
      Contact: "Contacto",
      Eemail: "Correo electrónico: [Insertar Correo]",
      Address: "Dirección: [Insertar Dirección]",
      termsAndConditionsTitle:
        "Al utilizar esta aplicación, aceptas los siguientes términos:",
      dataWeCollect: "Datos que recopilamos",
      agencyUserDetails:
        "Detalles de usuario de la agencia (nombre, correo electrónico, contraseña)",
      propertyInfo:
        "Información de la propiedad (imágenes, dirección, descripción)",
      clientVisitDetails:
        "Detalles de visita del cliente (nombre, correo electrónico, teléfono, recuento de visitantes, hora de visita, propiedad, ubicación)",
      howWeUseIt: "Cómo lo usamos",
      secureLogin: "Inicio de sesión seguro y acceso a la cuenta",
      scheduleManage: "Programar y gestionar visitas a propiedades",
      sendConfirmation:
        "Enviar correos electrónicos de confirmación a clientes y agencia",
      exportVisitData: "Exportar datos de visitas a Excel para registros",
      shareVisitInfo:
        "Compartir información de visitas a través de WhatsApp u otras aplicaciones",
      privacySecurity: "Privacidad y seguridad",
      dataIsolation:
        "Los datos de cada agencia están aislados — sin compartir entre agencias",
      passwordEncryption: "Las contraseñas están encriptadas",
      secureDataStorage:
        "Datos almacenados de forma segura y accesibles solo por usuarios autorizados",
      yourControl: "Tu control",
      accountControl:
        "Los usuarios de la agencia pueden actualizar o eliminar sus datos en cualquier momento. Para eliminar la cuenta, contáctenos en [Insertar Correo].",
      search: "Buscar",
      noLocation: "Ubicación no disponible",
      noApartmentsFound: "No se encontraron apartamentos",
      noContactsFound: "No se encontraron contactos",
      confirmLogout: "¿Estás seguro de que quieres cerrar sesión?",
      ok: "OK",
      cancel: "Cancelar",
      selectProperty: "Seleccionar propiedad",
      property: "Propiedad",
      visitTime: "Hora de la visita",
    },
  },
];

export const appLanguages: AppLanguage[] = [
  {
    id: "0",
    name: "English",
    code: "en",
  },
  {
    id: "1",
    name: "Spanish",
    code: "sp",
  },
];

export const visitDetails: VisitDetail[] = [
  {
    date: "Feb 20, 2024",
    numberOfVisitors: "2",
    numberOfInfants: "1",
    propertyAddress: "123 Male St, Springfield",
  },
];
