import { LanguageData, AppLanguage, VisitDetail } from "../../types/types";

export const languageData: LanguageData[] = [
  {
    locale: "en",
    translation: {
      welcomeBack: "Welcome Back!",
      pleaseLoginHere: "Please Login Here!",
      emailAddress: "Email Address",
      email: "E-mail",
      password: "Password",
      forgotPassword: "Forget Password?",
      rememberme: "Remember me",
      donthaveaccount: "Don't have account?",
      signup: "Sign up",
      or: "OR",
      signIn: "Login",
      pleaseRegisterHere: "Please Register Here!",
      fullname: "Full Name",
      confirmpassword: "Confirm password",
      role: "Role",
      alreadyhaveanaccount: "Already have an account?",
      TermsConditions: "Terms & Conditions",
      registerissucessfullyhaveenjoy: "Register is sucessfully have enjoy!",
      resetyourpassword: "Reset your password",
      enteryouremail: "Input your Email Address",
      rememberyourpassword: "Remember your password?",
      sendOtp: "SEND OTP",
      changePassword: "Change password",
      enteryournewpassword: "Create the new password",
      invalidEmail: "Please enter a valid email address",
      emailRequired: "Email is required",
      passwordRequired: "Password is required",
      passwordMin: "Password must be at least 6 characters long",
      fullnameRequired: "Full Name is required",
      roleRequired: "Role is required",
      selectRole: "Select Role",
      confirmpasswordRequired: "Confirm Password is required",
      passwordsDoNotMatch: "Passwords do not match",
      goodMorning: "Good Morning",
      seeAll: "See All",
      category: "Category",
      advertisements: "Advertisements",
      service: "Service",
      cleaning: "Cleaning",
      repairing: "Repairing",
      painting: "Painting",
      laundry: "Laundry",
      plumbing: "Plumbing",
      electrical: "Electrical",
      carpentry: "Carpentry",
      moving: "Moving",
      pestControl: "Pest Control",
      gardening: "Gardening",
      homeSecurity: "Home Security",
      etc: "etc",
      all: "All",
      reviews: "Reviews",
      editProfile: "Edit Profile",
      notifications: "Notifications",
      payments: "Payments",
      security: "Security",
      privacyPolicy: "Privacy Policy",
      helpCenter: "Help Center",
      inviteFriends: "Invite Friends",
      language: "Language",
      logout: "Logout",
      dateOfBirth: "Date of Birth",
      save: "Save",
      phoneNumber: "Phone Number",
      fullName: "Full Name",
      address: "Address",
      cardHolderName: "Card Holder Name",
      cardNumber: "Card Number",
      expiryDate: "Expiry Date",
      cvv: "CVV",
      proceedToPay: "Proceed to Pay",
      enterName: "Enter Name",
      deleteAccount: "Delete Account",
      deleteAccountConfirm: "Delete Account Confirm",
      deleteYourAccount: "Delete Your Account",
      enterYourPassword: "Enter Your Password",
      warning: "Warning",
      bookingHistory: "Booking History",
      savedPaymentMethods: "Saved Payment Methods",
      personalPreferences: "Personal Preferences",
      proceedInstruction: "Proceed Instruction",
      passwordPlaceholder: "Password Placeholder",
      delete: "Delete",
      warningDelete: "Warning Delete",
      title: "Title",
      description: "Description",
      price: "Price",
      location: "Location",
      book: "Book",
      AdFullView: "Ad Full View",
      deleteChat: "Delete Chat",
      areYourSureYouWant: "Are Your Sure You Want",
      typeamsg: "Type a message",
      request: "Request",
      upcoming: "Upcoming",
      ongoing: "Ongoing",
      completed: "Completed",
      canceled: "Canceled",
      accept: "Accept",
      cancel: "Cancel",
      bookingDetails: "Booking Details",
      pay: "Pay",
      amount: "Amount",
      vat: "VAT",
      total: "Total",
      bookmark: "Bookmark",
      ourservices: "Our Services",
      awayfromhome: "Away from Home",
      becleanisaplatform: "BeClean is a platform",
      personalizeyourexp: "Personalize your experience",
      getstarted: "Get Started",
      selectAppLanguage: "Select App Language",
      selectLanguage: "Select Language",
      priceError: "Price Error",
      imagesRequired: "Images Required",
      serviceName: "Service Name",
      servicePrice: "Service Price",
      servicePriceError: "Service Price Error",
      bookingDateTime: "Booking Date & Time",
      pinLocation: "Pin Location",
      submit: "Submit",
      additionalServices: "Additional Services",
      addService: "Add Service",
      categoryRequired: "Category Required",
      titleRequired: "Title Required",
      descriptionRequired: "Description Required",
      priceRequired: "Price Required",
      serviceNameRequired: "Service Name Required",
      servicePriceRequired: "Service Price Required",
      bookingRequired: "Booking Required",
      addressRequired: "Address Required",
      pinLocationRequired: "Pin Location Required",
      createAd: "Create Ad",
      selectCategory: "Select Category",
      edit: "Edit",
      myAds: "My Ads",
      services: "Services",
      jobs: "Jobs",
      createJob: "Create Job",
      createService: "Create Service",
      image: "Image",
      imageFullView: "Image Full View",
    },
  },
  {
    locale: "sp",
    translation: {
      welcomeBack: "¡Bienvenido de nuevo!",
      pleaseLoginHere: "¡Por favor, inicia sesión aquí!",
      emailAddress: "Dirección de correo electrónico",
      email: "Correo electrónico",
      password: "Contraseña",
      forgotPassword: "¿Olvidaste tu contraseña?",
      rememberme: "Recuérdame",
      donthaveaccount: "¿No tienes cuenta?",
      signup: "Regístrate",
      or: "O",
      signIn: "Iniciar sesión",
      pleaseRegisterHere: "¡Por favor, regístrate aquí!",
      fullname: "Nombre completo",
      confirmpassword: "Confirmar contraseña",
      role: "Rol",
      alreadyhaveanaccount: "¿Ya tienes una cuenta?",
      TermsConditions: "Términos y condiciones",
      registerissucessfullyhaveenjoy: "¡Registro exitoso, disfruta!",
      resetyourpassword: "Restablecer tu contraseña",
      enteryouremail: "Ingresa tu dirección de correo electrónico",
      rememberyourpassword: "¿Recuerdas tu contraseña?",
      sendOtp: "ENVIAR CÓDIGO",
      changePassword: "Cambiar contraseña",
      enteryournewpassword: "Crea la nueva contraseña",
      invalidEmail:
        "Por favor, ingresa una dirección de correo electrónico válida",
      emailRequired: "El correo electrónico es obligatorio",
      passwordRequired: "La contraseña es obligatoria",
      passwordMin: "La contraseña debe tener al menos 6 caracteres",
      fullnameRequired: "El nombre completo es obligatorio",
      roleRequired: "El rol es obligatorio",
      selectRole: "Seleccionar Rol",
      confirmpasswordRequired: "Confirmar contraseña es obligatorio",
      passwordsDoNotMatch: "Las contraseñas no coinciden",
      goodMorning: "Buenos días",
      seeAll: "Ver todo",
      category: "Categoría",
      advertisements: "Anuncios",
      service: "Servicio",
      cleaning: "Limpieza",
      repairing: "Reparación",
      painting: "Pintura",
      laundry: "Lavandería",
      plumbing: "Fontanería",
      electrical: "Eléctrico",
      carpentry: "Carpintería",
      moving: "Mudanza",
      pestControl: "Control de plagas",
      gardening: "Jardinería",
      homeSecurity: "Seguridad del hogar",
      etc: "etc",
      all: "Todo",
      reviews: "Reseñas",
      editProfile: "Editar perfil",
      notifications: "Notificaciones",
      payments: "Pagos",
      security: "Seguridad",
      privacyPolicy: "Política de privacidad",
      helpCenter: "Centro de ayuda",
      inviteFriends: "Invitar amigos",
      language: "Idioma",
      logout: "Cerrar sesión",
      dateOfBirth: "Fecha de nacimiento",
      save: "Guardar",
      phoneNumber: "Número de teléfono",
      fullName: "Nombre completo",
      address: "Dirección",
      cardHolderName: "Nombre del titular",
      cardNumber: "Número de tarjeta",
      expiryDate: "Fecha de vencimiento",
      cvv: "CVV",
      proceedToPay: "Proceder al pago",
      enterName: "Ingresar nombre",
      deleteAccount: "Eliminar cuenta",
      deleteAccountConfirm: "Confirmar eliminación de cuenta",
      deleteYourAccount: "Eliminar tu cuenta",
      enterYourPassword: "Ingresa tu contraseña",
      warning: "Advertencia",
      bookingHistory: "Historial de reservas",
      savedPaymentMethods: "Métodos de pago guardados",
      personalPreferences: "Preferencias personales",
      proceedInstruction: "Instrucciones para proceder",
      passwordPlaceholder: "Contraseña",
      delete: "Eliminar",
      warningDelete: "Advertencia de eliminación",
      title: "Título",
      description: "Descripción",
      price: "Precio",
      location: "Ubicación",
      book: "Reservar",
      AdFullView: "Vista completa del anuncio",
      deleteChat: "Eliminar chat",
      areYourSureYouWant: "¿Estás seguro de que quieres?",
      typeamsg: "Escribe un mensaje",
      request: "Solicitud",
      upcoming: "Próximos",
      ongoing: "En curso",
      completed: "Completados",
      canceled: "Cancelados",
      accept: "Aceptar",
      cancel: "Cancelar",
      bookingDetails: "Detalles de la reserva",
      pay: "Pagar",
      amount: "Cantidad",
      vat: "IVA",
      total: "Total",
      bookmark: "Marcador",
      ourservices: "Nuestros servicios",
      awayfromhome: "Fuera de casa",
      becleanisaplatform: "BeClean es una plataforma",
      personalizeyourexp: "Personaliza tu experiencia",
      getstarted: "Comenzar",
      selectAppLanguage: "Seleccionar idioma de la aplicación",
      selectLanguage: "Seleccionar idioma",
      priceError: "Error de precio",
      imagesRequired: "Imágenes requeridas",
      serviceName: "Nombre del servicio",
      servicePrice: "Precio del servicio",
      servicePriceError: "Error en el precio del servicio",
      bookingDateTime: "Fecha y hora de la reserva",
      pinLocation: "Marcar ubicación",
      submit: "Enviar",
      additionalServices: "Servicios adicionales",
      addService: "Agregar servicio",
      categoryRequired: "Categoría requerida",
      titleRequired: "Título requerido",
      descriptionRequired: "Descripción requerida",
      priceRequired: "Precio requerido",
      serviceNameRequired: "Nombre del servicio requerido",
      servicePriceRequired: "Precio del servicio requerido",
      bookingRequired: "Reserva requerida",
      addressRequired: "Dirección requerida",
      pinLocationRequired: "Ubicación requerida",
      createAd: "Crear anuncio",
      selectCategory: "Seleccionar categoría",
      edit: "Editar",
      myAds: "Mis anuncios",
      services: "Servicios",
      jobs: "Trabajos",
      createJob: "Crear trabajo",
      createService: "Crear servicio",
      image: "Imagen",
      imageFullView: "Vista completa de la imagen",
    },
  },
];

export const appLanguages: AppLanguage[] = [
  {
    id: "0",
    name: "English",
    code: "en",
  },
  {
    id: "1",
    name: "Spanish",
    code: "sp",
  },
];

export const visitDetails: VisitDetail[] = [
  {
    date: "Feb 20, 2024",
    numberOfVisitors: "2",
    numberOfInfants: "1",
    propertyAddress: "123 Male St, Springfield",
  },
];
